// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/github/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/github/client.go -destination=pkg/github/mock_client.go -package=github
//

// Package github is a generated GoMock package.
package github

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetMergedPR mocks base method.
func (m *MockClient) GetMergedPR(repoPath, branch string) (*PRInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMergedPR", repoPath, branch)
	ret0, _ := ret[0].(*PRInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMergedPR indicates an expected call of GetMergedPR.
func (mr *MockClientMockRecorder) GetMergedPR(repoPath, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergedPR", reflect.TypeOf((*MockClient)(nil).GetMergedPR), repoPath, branch)
}
